apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-server
        image: mvpstudio/k8-hello-world:1
        resources:
          limits:
            cpu: 0.25
            memory: 250Mi
          requests:
            cpu: 0.25
            memory: 250Mi
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsecrets
                key: password
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: pgsecrets
                key: username
          - name: DATABASE_HOST
            value: postgres.hello-world:5432
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
